name: produitsapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  firebase_auth: ^5.3.3
  firebase_core: ^3.8.0
  flutter:
    sdk: flutter
  flutter_slidable: ^3.1.1
  image_picker: ^1.1.2
  cloud_firestore: ^5.5.1
  supabase_flutter: ^2.8.1
  firebase_storage: ^12.3.7
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  firebase_ui_auth: ^1.0.0
 

flutter:
  uses-material-design: true
  assets:
    - assets/images/